### ISSUE TITLE
«Could not get socket :6081: Address already in use» / «Syntax check failed, not restarting» on `service varnish restart` 

### ISSUE THREAD

**Issue by dmitrii-fediuk** [vegandthecity/server#15]
[https://df.tips/t/1015](https://df.tips/t/1015)

![01](https://user-images.githubusercontent.com/83204/79641512-c5760380-81b9-11ea-850d-0bac3b8810e0.png)

Related to https://github.com/vegandthecity/server/issues/14

**Comment by dmitrii-fediuk** [comment]
Fixed by https://github.com/varnishcache/pkg-varnish-cache/issues/75#issuecomment-316727624

**Comment by bobemoe** [comment]
Looks like the fix is from 2017... so what version of varnish should it be included in? 

I'm using varnish-6.1.1 on Debian 10 (2019) and still seeing this issue!
